python mainczr.py --dataset Strawberry --num-shapelets 40 --pruning-percentile 30
python mainczr.py --dataset Strawberry --num-shapelets 40 --pruning-percentile 40
python mainczr.py --dataset Strawberry --num-shapelets 40 --pruning-percentile 50
python mainczr.py --dataset Strawberry --num-shapelets 40 --pruning-percentile 60
python mainczr.py --dataset Strawberry --num-shapelets 50 --pruning-percentile 30
python mainczr.py --dataset Strawberry --num-shapelets 50 --pruning-percentile 40
python mainczr.py --dataset Strawberry --num-shapelets 50 --pruning-percentile 50
python mainczr.py --dataset Strawberry --num-shapelets 50 --pruning-percentile 60
python mainczr.py --dataset Strawberry --num-shapelets 60 --pruning-percentile 30
python mainczr.py --dataset Strawberry --num-shapelets 60 --pruning-percentile 40
python mainczr.py --dataset Strawberry --num-shapelets 60 --pruning-percentile 50
python mainczr.py --dataset Strawberry --num-shapelets 60 --pruning-percentile 60
python mainczr.py --dataset Strawberry --num-shapelets 80 --pruning-percentile 30
python mainczr.py --dataset Strawberry --num-shapelets 80 --pruning-percentile 40
python mainczr.py --dataset Strawberry --num-shapelets 80 --pruning-percentile 50
python mainczr.py --dataset Strawberry --num-shapelets 80 --pruning-percentile 60
python mainczr.py --dataset Earthquakes --num-shapelets 40 --pruning-percentile 30
python mainczr.py --dataset Earthquakes --num-shapelets 40 --pruning-percentile 40
python mainczr.py --dataset Earthquakes --num-shapelets 40 --pruning-percentile 50
python mainczr.py --dataset Earthquakes --num-shapelets 40 --pruning-percentile 60
python mainczr.py --dataset Earthquakes --num-shapelets 50 --pruning-percentile 30
python mainczr.py --dataset Earthquakes --num-shapelets 50 --pruning-percentile 40
python mainczr.py --dataset Earthquakes --num-shapelets 50 --pruning-percentile 50
python mainczr.py --dataset Earthquakes --num-shapelets 50 --pruning-percentile 60
python mainczr.py --dataset Earthquakes --num-shapelets 60 --pruning-percentile 30
python mainczr.py --dataset Earthquakes --num-shapelets 60 --pruning-percentile 40
python mainczr.py --dataset Earthquakes --num-shapelets 60 --pruning-percentile 50
python mainczr.py --dataset Earthquakes --num-shapelets 60 --pruning-percentile 60
python mainczr.py --dataset Earthquakes --num-shapelets 80 --pruning-percentile 30
python mainczr.py --dataset Earthquakes --num-shapelets 80 --pruning-percentile 40
python mainczr.py --dataset Earthquakes --num-shapelets 80 --pruning-percentile 50
python mainczr.py --dataset Earthquakes --num-shapelets 80 --pruning-percentile 60
python mainczr.py --dataset WormsTwoClass --num-shapelets 40 --pruning-percentile 30
python mainczr.py --dataset WormsTwoClass --num-shapelets 40 --pruning-percentile 40
python mainczr.py --dataset WormsTwoClass --num-shapelets 40 --pruning-percentile 50
python mainczr.py --dataset WormsTwoClass --num-shapelets 40 --pruning-percentile 60
python mainczr.py --dataset WormsTwoClass --num-shapelets 50 --pruning-percentile 30
python mainczr.py --dataset WormsTwoClass --num-shapelets 50 --pruning-percentile 40
python mainczr.py --dataset WormsTwoClass --num-shapelets 50 --pruning-percentile 50
python mainczr.py --dataset WormsTwoClass --num-shapelets 50 --pruning-percentile 60
python mainczr.py --dataset WormsTwoClass --num-shapelets 60 --pruning-percentile 30
python mainczr.py --dataset WormsTwoClass --num-shapelets 60 --pruning-percentile 40
python mainczr.py --dataset WormsTwoClass --num-shapelets 60 --pruning-percentile 50
python mainczr.py --dataset WormsTwoClass --num-shapelets 60 --pruning-percentile 60
python mainczr.py --dataset WormsTwoClass --num-shapelets 80 --pruning-percentile 30
python mainczr.py --dataset WormsTwoClass --num-shapelets 80 --pruning-percentile 40
python mainczr.py --dataset WormsTwoClass --num-shapelets 80 --pruning-percentile 50
python mainczr.py --dataset WormsTwoClass --num-shapelets 80 --pruning-percentile 60
